// SPDX-License-Identifier: BSD-3-Clause
//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
)

func main() {
	text, err := os.ReadFile("../../LICENSE")
	if err != nil {
		log.Fatal(err)
	}
	var source bytes.Buffer
	fmt.Fprintln(&source, "// Code generated by go generate ./internal/license; DO NOT EDIT.")
	fmt.Fprintln(&source, "\npackage license")
	fmt.Fprintln(&source, "\n// Text contains this project's license and all third-party notices.")
	fmt.Fprint(&source, `const Text = ""`)
	for _, line := range bytes.SplitAfter(text, []byte("\n")) {
		if len(line) != 0 {
			fmt.Fprintf(&source, " +\n%q", line)
		}
	}
	source.WriteByte('\n')
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("text_generated.go", formatted, 0o644); err != nil {
		log.Fatal(err)
	}
}
